-- Daily Pulse: one row per user per day, storing raw scores + normalised points

create table public.daily_scores (
  id               bigint generated by default as identity primary key,
  user_id          uuid    references public.profiles(id) on delete cascade not null,
  challenge_date   date    not null,
  reaction_ms      numeric,
  typing_wpm       numeric,
  maths_correct    numeric,
  memory_rounds    numeric,
  reaction_points  integer not null default 0,
  typing_points    integer not null default 0,
  maths_points     integer not null default 0,
  memory_points    integer not null default 0,
  composite_score  integer not null default 0,
  created_at       timestamp with time zone default timezone('utc', now()) not null,
  unique (user_id, challenge_date)
);

alter table public.daily_scores enable row level security;

-- Anyone can read the leaderboard
create policy "daily_scores: public read"
  on public.daily_scores for select using (true);

-- Users can only insert their own score (one per day enforced by unique constraint)
create policy "daily_scores: insert own"
  on public.daily_scores for insert
  with check (auth.uid() = user_id);

-- Fast daily leaderboard lookups
create index idx_daily_scores_date_composite
  on public.daily_scores (challenge_date, composite_score desc);

-- Fast streak computation
create index idx_daily_scores_user_date
  on public.daily_scores (user_id, challenge_date desc);
