-- ============================================================
-- BrainyPulse Database Initialization
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================

-- Create Secure Profiles Linked Directly to Supabase Auth Users
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique not null check (char_length(username) >= 3),
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Normalized Core Global Scores Storage Engine
create table public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  tool_type text not null check (tool_type in ('typing', 'memory', 'maths', 'reaction')),
  score_value numeric not null,
  accuracy numeric default 100,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- High-Frequency Indexing Framework for Blazing-Fast Leaderboards
create index idx_leaderboard_query_engine on public.scores (tool_type, score_value desc);

-- Turn on Row Level Security Verification
alter table public.profiles enable row level security;
alter table public.scores enable row level security;

-- Security Policies: Profiles
create policy "Allow public read access to profiles"
  on public.profiles for select using (true);

create policy "Allow users to update their own profile"
  on public.profiles for update using (auth.uid() = id);

create policy "Allow users to insert their own profile"
  on public.profiles for insert with check (auth.uid() = id);

-- Security Policies: Scores
create policy "Allow public read access to scores"
  on public.scores for select using (true);

create policy "Allow authenticated users to insert their own score"
  on public.scores for insert with check (auth.uid() = user_id);

-- ============================================================
-- Auto-create Profile on New User Registration
-- This trigger fires after a new user signs up via Supabase Auth
-- and creates a matching row in public.profiles automatically.
-- ============================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'username',
      split_part(new.email, '@', 1)
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
